/* Weavefall mobile offline cache — generated by tools/build-mobile.py; do not hand-edit.
   Caches the app shell and every EA asset so the game keeps running after the
   local dev server (a-Shell on iOS) is suspended. Cache-first: a GET that once
   succeeds is served from cache forever, until the build version changes. */
const VERSION = "e0a2e0f26e62";
const CACHE = "weavefall-mobile-" + VERSION;

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k.startsWith("weavefall-mobile-") && k !== CACHE)
          .map((k) => caches.delete(k))
    );
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === "basic") cache.put(req, res.clone());
      return res;
    } catch (err) {
      const stale = await cache.match(req);
      if (stale) return stale;
      throw err;
    }
  })());
});
