// @ts-check
const { test, expect } = require('@playwright/test');

/* Slice 3 of the iPhone plan: the mobile build is installable to the iOS Home
   Screen as a standalone app. The manifest, icon, and head wiring are all
   generated by tools/build-mobile.py — nothing under mobile/ is hand-edited,
   and the icon is an existing EA asset served byte-for-byte, not new art. */

test.describe('mobile build PWA shell', () => {
  test('serves a valid standalone manifest, linked from the page head', async ({ page, request }) => {
    await page.goto('/mobile/index.html', { waitUntil: 'domcontentloaded' });

    const manifestHref = await page.getAttribute('link[rel="manifest"]', 'href');
    expect(manifestHref, 'the page must link its manifest').toBeTruthy();

    const res = await request.get('/mobile/' + manifestHref);
    expect(res.status()).toBe(200);
    const manifest = await res.json();

    expect(manifest.name).toBeTruthy();
    expect(manifest.display).toBe('standalone');
    expect(Array.isArray(manifest.icons)).toBe(true);
    expect(manifest.icons.length).toBeGreaterThan(0);

    // every declared icon actually resolves and is a PNG
    for (const icon of manifest.icons) {
      const ir = await request.get('/mobile/' + icon.src);
      expect(ir.status(), icon.src).toBe(200);
      expect((await ir.body()).subarray(1, 4).toString(), icon.src).toBe('PNG');
    }
  });

  test('wires the iOS home-screen head tags with a real touch icon', async ({ page, request }) => {
    await page.goto('/mobile/index.html', { waitUntil: 'domcontentloaded' });

    const touchIcon = await page.getAttribute('link[rel="apple-touch-icon"]', 'href');
    expect(touchIcon, 'apple-touch-icon must be linked').toBeTruthy();
    const ir = await request.get('/mobile/' + touchIcon);
    expect(ir.status()).toBe(200);
    expect((await ir.body()).subarray(1, 4).toString()).toBe('PNG');

    const capable = await page.getAttribute('meta[name="apple-mobile-web-app-capable"]', 'content');
    expect(capable).toBe('yes');
  });
});
