#!/usr/bin/env python3
"""Generate the slim mobile build from the canonical single-file index.html.

The canonical index.html is the single self-contained source of truth and is
NEVER modified by this script. We only read it. The art/audio rules still hold:
every asset is written out byte-for-byte (no recolor, no re-encode), just stored
as a real file instead of an inline base64 data URI.

Output:
  mobile/index.html        slim HTML (data URIs -> relative asset paths)
  mobile/assets/imgNNNN.*  extracted images (webp/png/jpg)
  mobile/assets/sndNNNN.*  extracted audio (mp3)

Run from the repo root:  python3 tools/build-mobile.py
"""
import base64
import hashlib
import json
import pathlib
import re
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "index.html"
OUT = ROOT / "mobile"
ASSETS = OUT / "assets"

EXT = {
    "image/webp": "webp",
    "image/png": "png",
    "image/jpeg": "jpg",
    "audio/mpeg": "mp3",
}

# data:<mime>;base64,<blob> — blob runs until the closing quote (base64 charset
# only), so it never overruns into the next token.
PATTERN = re.compile(
    r"data:(image/webp|image/png|image/jpeg|audio/mpeg);base64,([A-Za-z0-9+/=]+)"
)

# The worker that makes the phone-only path survive a sleeping server. Served at
# mobile/sw.js (scope mobile/), it serves cache-first and stores every same-origin
# GET the first time it succeeds, so partial progress across reloads is permanent.
SW_JS = r"""/* Weavefall mobile offline cache — generated by tools/build-mobile.py; do not hand-edit.
   Caches the app shell and every EA asset so the game keeps running after the
   local dev server (a-Shell on iOS) is suspended. Cache-first: a GET that once
   succeeds is served from cache forever, until the build version changes. */
const VERSION = "__VERSION__";
const CACHE = "weavefall-mobile-" + VERSION;

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k.startsWith("weavefall-mobile-") && k !== CACHE)
          .map((k) => caches.delete(k))
    );
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === "basic") cache.put(req, res.clone());
      return res;
    } catch (err) {
      const stale = await cache.match(req);
      if (stale) return stale;
      throw err;
    }
  })());
});
"""

# Injected just before </body> in the slim build only. Registers the worker and
# proactively pulls every asset into the cache (the worker stores them), with a
# small progress pill. Dormant unless the page is a secure context, so it does
# nothing on a plain-http LAN ip and only kicks in on localhost / https.
REGISTER_SNIPPET = r"""<script>
/* offline cache (phone-only path): cache every EA asset so the map paints even
   after iOS suspends the local a-Shell server. Secure-context only (localhost /
   https); over a plain-http LAN ip this returns immediately and changes nothing. */
(function () {
  if (!("serviceWorker" in navigator) || !window.isSecureContext) return;
  navigator.serviceWorker.register("sw.js", { updateViaCache: "none" }).catch(function () {});

  var pill;
  function say(t) {
    if (!pill) {
      pill = document.createElement("div");
      pill.style.cssText =
        "position:fixed;left:50%;transform:translateX(-50%);bottom:8px;z-index:99999;" +
        "background:rgba(20,17,30,.92);color:#e8e2d6;font:600 12px/1.4 system-ui,sans-serif;" +
        "padding:6px 12px;border-radius:14px;border:1px solid rgba(238,214,156,.35);" +
        "pointer-events:none;max-width:90vw;text-align:center";
      document.body.appendChild(pill);
    }
    pill.textContent = t;
  }
  function done() { if (pill) { pill.remove(); pill = null; } }
  function flag(k, v) {
    try { return v === undefined ? localStorage.getItem(k) : localStorage.setItem(k, v); }
    catch (e) { return null; }
  }

  async function warm() {
    var m;
    try { m = await (await fetch("asset-manifest.json", { cache: "no-store" })).json(); }
    catch (e) { return; }
    var list = m && m.assets;
    if (!Array.isArray(list) || !list.length) return;
    if (flag("wf-warmed") === m.version) return;          /* already fully cached this build */
    var total = list.length, seen = 0, failed = 0, i = 0;
    say("Caching art for offline… 0%");
    async function pull() {
      while (i < list.length) {
        var url = list[i++];
        try { await fetch(url); } catch (e) { failed++; }
        seen++;
        if (seen % 12 === 0 || seen === total)
          say("Caching art for offline… " + Math.round((seen / total) * 100) + "%");
      }
    }
    var lanes = [];
    for (var k = 0; k < 6; k++) lanes.push(pull());
    await Promise.all(lanes);
    if (failed) {
      say("Offline cache " + Math.round(((total - failed) / total) * 100) +
          "% — wake a-Shell, return here, reload to finish");
      setTimeout(done, 9000);
    } else {
      flag("wf-warmed", m.version);
      say("Offline cache complete ✓ — the server can sleep now");
      setTimeout(done, 3000);
    }
  }
  if (document.readyState === "complete") setTimeout(warm, 1500);
  else addEventListener("load", function () { setTimeout(warm, 1500); });
})();
</script>
"""


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    ASSETS.mkdir(parents=True)

    src = SRC.read_text(encoding="utf-8")

    by_hash: dict[str, str] = {}          # content hash -> relative path
    counters = {"img": 0, "snd": 0}
    stats = {"img": 0, "snd": 0, "img_bytes": 0, "snd_bytes": 0}

    def replace(match: re.Match) -> str:
        mime, b64 = match.group(1), match.group(2)
        raw = base64.b64decode(b64)
        digest = hashlib.sha1(raw).hexdigest()
        if digest in by_hash:
            return by_hash[digest]          # dedup identical assets
        kind = "snd" if mime.startswith("audio") else "img"
        counters[kind] += 1
        rel = f"assets/{kind}{counters[kind]:04d}.{EXT[mime]}"
        (OUT / rel).write_bytes(raw)
        by_hash[digest] = rel
        stats[kind] += 1
        stats[f"{kind}_bytes"] += len(raw)
        return rel

    slim = PATTERN.sub(replace, src)

    # ---- mobile offline cache (phone-only path) -------------------------
    # iOS suspends the local a-Shell server shortly after you switch away, so
    # the ~50MB of EA art can't finish streaming and the canvas paints its
    # "image not ready" fallback. Ship a service worker that caches every asset
    # on first fetch (durably, across reloads) plus a page hook that warms the
    # cache up front, so the game keeps running once the server goes to sleep.
    assets = sorted(set(by_hash.values()))
    version = hashlib.sha1(
        (slim + "\n".join(assets) + SW_JS + REGISTER_SNIPPET).encode("utf-8")
    ).hexdigest()[:12]

    (OUT / "asset-manifest.json").write_text(
        json.dumps({"version": version, "assets": assets}), encoding="utf-8"
    )
    (OUT / "sw.js").write_text(SW_JS.replace("__VERSION__", version), encoding="utf-8")

    idx = slim.rfind("</body>")
    if idx == -1:
        raise SystemExit("build-mobile: no </body> to attach the offline-cache hook")
    slim = slim[:idx] + REGISTER_SNIPPET + slim[idx:]

    (OUT / "index.html").write_text(slim, encoding="utf-8")

    leftover = len(re.findall(r"data:(?:image|audio)/", slim))
    mb = 1024 * 1024
    print(f"source index.html : {len(src)/mb:6.2f} MB")
    print(f"slim   index.html : {len(slim)/mb:6.2f} MB")
    print(f"images written    : {stats['img']:>5}  ({stats['img_bytes']/mb:6.2f} MB)")
    print(f"audio  written    : {stats['snd']:>5}  ({stats['snd_bytes']/mb:6.2f} MB)")
    print(f"unique assets     : {len(by_hash):>5}")
    print(f"offline cache     : sw.js + asset-manifest.json  (build {version})")
    print(f"data: URIs left in slim html : {leftover}  (must be 0)")


if __name__ == "__main__":
    main()
